# Generated by Django 4.2.11 on 2024-05-11 07:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_alter_student_admission_fees_and_more'),
        ('academic_year', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_received_by', models.CharField(max_length=100)),
                ('manual_fee_receipt_number', models.CharField(max_length=5)),
                ('fees_paid_on', models.DateTimeField(auto_now_add=True)),
                ('discount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('amount_paid', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
            ],
        ),
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Mon', 'Monthly'), ('Adm', 'Admission'), ('Exm', 'Examination'), ('Brd', 'Board'), ('Prc', 'Practical'), ('Oth', 'Other')], max_length=3)),
                ('other_charges', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('description', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_year.academic_year')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=6)),
                ('dues_remaining', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('paid_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.fees')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.feereceipt')),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fees.studentfee')),
            ],
        ),
        migrations.AddField(
            model_name='feereceipt',
            name='student_fees',
            field=models.ManyToManyField(through='fees.StudentFeeReceipt', to='fees.studentfee'),
        ),
    ]
