# Generated by Django 4.0 on 2024-08-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_feereceipt_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feereceipt',
            name='student_fees',
            field=models.ManyToManyField(through='fees.StudentFeeReceipt', to='fees.StudentFee'),
        ),
    ]
