# Generated by Django 4.0 on 2024-08-23 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_default_amount_alter_expenses_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyincome',
            name='discount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
