# Generated by Django 4.2.11 on 2024-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='b_form_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
