# Generated by Django 4.2.11 on 2024-05-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_admission_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyinformation',
            name='father_cell_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='father_nic_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='father_office_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='father_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='mother_cell_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='mother_nic_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='familyinformation',
            name='mother_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='b_form_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
